service: quiztopia
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  profile: HerrPablito
  iam:
    role: arn:aws:iam::724975227532:role/pabbe-role
  deploymentMethod: direct
  environment:
    DYNAMODB_QUIZ_TABLE: quizDb
    DYNAMODB_REGION: 'eu-north-1'    
useDotenv: true

plugins: 
  - serverless-webpack

package:
  individually: true

custom:
  webpack:
    includeModules: true

functions:
  getAllQuiz:
    handler: functions/getAllQuiz/index.handler
    events:
      - httpApi:
          path: '/api/Quiz'
          method: GET
  createQuiz:
    handler: functions/createQuiz/index.handler
    events:
      - httpApi:
          path: '/api/createQuiz'
          method: POST
  # updateNote:
  #   handler: functions/updateNote/index.handler
  #   events:
  #     - httpApi:
  #         path: '/api/events/{noteId}'
  #         method: PUT
  deleteQuiz:
    handler: functions/deleteQuiz/index.handler
    events:
      - httpApi:
          path: '/api/events/{quizId}'
          method: DELETE
  signup:
    handler: functions/signup/index.handler
    events:
      - httpApi:
          path: '/api/user/signup'
          method: POST
  login:
    handler: functions/login/index.handler
    events:
      - httpApi:
          path: '/api/user/login'
          method: POST
resources:
  Resources:
    quizDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: quizDb
        AttributeDefinitions:
          - AttributeName: quizId
            AttributeType: S
        KeySchema:
          - AttributeName: quizId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
    usersDb:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: usersDb
        AttributeDefinitions:
          - AttributeName: userName
            AttributeType: S
        KeySchema:
          - AttributeName: userName
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST


